#!/usr/bin/perl -w

use strict;

#my $ADB = '/home/keithw/android/android-sdk-linux/platform-tools/adb';
my $ADB= '/home/anirudh/OSDIWork/android-sdk-linux/platform-tools//adb';
my %devices = ( A => '0149A44C1000D00C' );

my ( $device, @command ) = @ARGV;

die unless exists $devices{ $device };

exec { $ADB } ( 'adb', '-s', $devices{ $device }, @command );
